mongo:
  auth: false
  username: ''
  password: ''

banned-players:
  can-join: false

redis:
  auth: false
  password: ''

rankHandler:
  clean: true

Punish:
  enabled: true
  commands:
    - alert %PLAYER% is trying to exploit Log4J!
useFilter: true
hookIntoPackets: true

Announcements:
  Time: 3
  List:
    - "&8[&6&oTIP&8] &eFollow us on twitter @CobelPvPNetwork."
    - "&8[&4&o!&8] &cBe sure to read our rules ./Rules"
    - "&8[&6&oTIP&8] &eYou can join to our &9discord &ecommunity &9./discord."
    - "&8[&6&oStore&8] &eCheck out at our Store: &6cobelpvp.tebex.io."
    - "&8[&4&oWarn&8] &cButterfly clicking are not allowed and may result in a perm ban."